services:
  web:
    build: .
    container_name: web
    volumes:
      - ./app:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      - SECRET_KEY=some_random_secret_key
      - DEBUG=False
      - DB_URL=${DB_URL}
      - IS_PROD=True
