services:
  web:
    build: .
    container_name: web
    volumes:
      - ./app:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      - SECRET_KEY=...
      - DEBUG=False
      - PENNY_WISE_DB_NAME=...
      - PENNY_WISE_DB_USER=...
      - PENNY_WISE_DB_PASSWORD=...
      - PENNY_WISE_DB_USER_HOST=...
      - PENNY_WISE_DB_PORT=...
