# Generated by Django 5.1.6 on 2025-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
