services:
  web:
    depends_on:
      - db
    env_file:
      - ../env/.env.prod

  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - ../env/.env.prod
    ports:
      - "5434:5432"
    volumes:
      - ../app/pgdata:/var/lib/postgresql/data
