services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - ../env/.env.tests


  web:
    depends_on:
      - db
    env_file:
      - ../env/.env.tests