services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - ../env/.env.tests
    volumes:
      - /var/lib/postgresql/data


  web:
    depends_on:
      - db
    env_file:
      - ../env/.env.tests
    environment:
      - PENNY_WISE_DB_HOST=db
      - PENNY_WISE_DB_PORT=5432
