services:
  web:
    env_file:
      - ../env/.env.prod # file .env.prod file is supposed to be added on prod

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: penny_db
      POSTGRES_USER: penny_user
      POSTGRES_PASSWORD: penny_password
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data