services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - ../env/.env.tests
    volumes:
      - pgdata_test:/var/lib/postgresql/data


  web:
    depends_on:
      - db
    env_file:
      - ../env/.env.tests


volumes:
  pgdata_test: