name: Django Tests (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IS_DB_CONNECTION_OVER_URL: false
      DB_URL: ""
      PENNY_WISE_DB_NAME: test_db
      PENNY_WISE_DB_USER: test_user
      PENNY_WISE_DB_PASSWORD: test_pass
      PENNY_WISE_DB_HOST: db
      PENNY_WISE_DB_PORT: 5432

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d --build

      - name: Run tests inside container
        run: |
          docker compose exec -T web python manage.py test --verbosity=2

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
