name: Django Tests (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          cd docker
          docker compose -f docker-compose.yaml -f docker-compose.tests.yaml up -d --build
          docker compose ps
          docker compose logs web
          docker compose logs db

      - name: Wait for Postgres to be ready
        run: |
          cd docker
          for i in {1..15}; do
            echo "Checking Postgres availability ($i/15)..."
            docker compose -f docker-compose.yaml -f docker-compose.tests.yaml exec -T db pg_isready -U test_user && exit 0
            sleep 2
          done
          echo "Postgres failed to start in time" >&2
          exit 1

      - name: show containers logs
        run: |
          cd docker
          docker compose logs web
          docker compose logs db

      - name: Run tests
        run: |
          cd docker
          docker compose exec web pytest

      - name: Show server logs
        if: always()
        run: |
          cd docker
          docker compose logs web

      - name: Stop Docker Compose
        if: always()
        run: |
          cd docker
          docker compose down
