name: Django Tests (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IS_DB_CONNECTION_OVER_URL: false
      DB_URL: ""
      PENNY_WISE_DB_NAME: test_db
      PENNY_WISE_DB_USER: test_user
      PENNY_WISE_DB_PASSWORD: test_pass
      PENNY_WISE_DB_HOST: db
      PENNY_WISE_DB_PORT: 5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.tests.yaml up -d --build
          docker compose ps

      - name: Check logs
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.tests.yaml logs db

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..15}; do
            echo "Checking Postgres availability ($i/15)..."
            docker compose -f docker-compose.yaml -f docker-compose.tests.yaml exec -T db pg_isready -U test_user && exit 0
            sleep 2
          done
          echo "Postgres failed to start in time" >&2
          exit 1

      - name: Check db ready
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.tests.yaml exec db pg_isready -U test_user

      - name: Run tests inside container
        run: |
          docker compose exec -T web python manage.py test --verbosity=2

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
