name: Django Tests (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Export .env.tests into env
#        run: |
#          echo "Reading .env.tests into environment..."
#          while IFS='=' read -r key value; do
#            if [[ ! "$key" =~ ^# && "$key" != "" ]]; then
#              echo "$key=$value" >> "$GITHUB_ENV"
#            fi
#          done < .env.tests

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.tests.yaml up -d --build
          docker compose ps

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..15}; do
            echo "Checking Postgres availability ($i/15)..."
            docker compose -f docker-compose.yaml -f docker-compose.tests.yaml exec -T db pg_isready -U test_user && exit 0
            sleep 2
          done
          echo "Postgres failed to start in time" >&2
          exit 1

      - name: Run tests inside container
        run: |
          docker compose exec -T web python manage.py test --verbosity=2

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
