name: Django Tests (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IS_DB_CONNECTION_OVER_URL: false
      PENNY_WISE_DB_NAME: test_db
      PENNY_WISE_DB_USER: test_user
      PENNY_WISE_DB_PASSWORD: test_pass
      PENNY_WISE_DB_HOST: db
      PENNY_WISE_DB_PORT: 5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d --build

      - name: Run tests inside container
        run: |
          docker compose exec -T web python manage.py test --verbosity=2

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
