name: Django Tests (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.tests.yaml up -d --build

      - name: Run tests inside container
        run: |
          docker compose exec -T web python manage.py test --verbosity=2

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
