name: Django Tests (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          cd docker
          docker compose -f docker-compose.yaml -f docker-compose.tests.yaml up -d --build
          docker compose ps

      - name: Wait Django app is ready
        run: |
          cd docker
          for i in {1..15}; do
            echo "Checking if Django is up ($i/15)..."
            if curl -s --fail http://localhost > /dev/null; then
              echo "Django is ready!"
              exit 0
            fi
            echo "Django is not ready yet..."
            sleep 2
          done
          echo "Django failed to start in time." >&2
          docker compose logs web
          exit 1

      - name: Run tests
        run: |
          cd docker
          docker compose exec web pytest


      - name: Stop Docker Compose
        if: always()
        run: |
          cd docker
          docker compose down
